// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: transaction.proto

package cn.hyperchain.sdk.transaction.proto;

public final class TransactionValueProto {
  private TransactionValueProto() {}
  public static void registerAllExtensions(
          com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
          com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
            (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface TransactionValueOrBuilder extends
          // @@protoc_insertion_point(interface_extends:cn.hyperchain.sdk.rpc.Transaction.proto.TransactionValue)
          com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int64 price = 1;</code>
     */
    long getPrice();

    /**
     * <code>int64 gasLimit = 2;</code>
     */
    long getGasLimit();

    /**
     * <code>int64 amount = 3;</code>
     */
    long getAmount();

    /**
     * <code>bytes payload = 4;</code>
     */
    com.google.protobuf.ByteString getPayload();

    /**
     * <code>bytes encryptedAmount = 5;</code>
     */
    com.google.protobuf.ByteString getEncryptedAmount();

    /**
     * <code>bytes homomorphicAmount = 6;</code>
     */
    com.google.protobuf.ByteString getHomomorphicAmount();

    /**
     * <code>bytes homomorphicBalance = 7;</code>
     */
    com.google.protobuf.ByteString getHomomorphicBalance();

    /**
     * <code>.cn.hyperchain.sdk.rpc.Transaction.proto.TransactionValue.Opcode op = 8;</code>
     */
    int getOpValue();
    /**
     * <code>.cn.hyperchain.sdk.rpc.Transaction.proto.TransactionValue.Opcode op = 8;</code>
     */
    TransactionValue.Opcode getOp();

    /**
     * <code>bytes extra = 9;</code>
     */
    com.google.protobuf.ByteString getExtra();

    /**
     * <code>bytes extraId = 10;</code>
     */
    com.google.protobuf.ByteString getExtraId();

    /**
     * <code>.cn.hyperchain.sdk.rpc.Transaction.proto.TransactionValue.VmType vmType = 11;</code>
     */
    int getVmTypeValue();
    /**
     * <code>.cn.hyperchain.sdk.rpc.Transaction.proto.TransactionValue.VmType vmType = 11;</code>
     */
    TransactionValue.VmType getVmType();
  }
  /**
   * Protobuf type {@code cn.hyperchain.sdk.rpc.Transaction.proto.TransactionValue}
   */
  public  static final class TransactionValue extends
          com.google.protobuf.GeneratedMessageV3 implements
          // @@protoc_insertion_point(message_implements:cn.hyperchain.sdk.rpc.Transaction.proto.TransactionValue)
          TransactionValueOrBuilder {
    private static final long serialVersionUID = 0L;
    // Use TransactionValue.newBuilder() to construct.
    private TransactionValue(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private TransactionValue() {
      payload_ = com.google.protobuf.ByteString.EMPTY;
      encryptedAmount_ = com.google.protobuf.ByteString.EMPTY;
      homomorphicAmount_ = com.google.protobuf.ByteString.EMPTY;
      homomorphicBalance_ = com.google.protobuf.ByteString.EMPTY;
      op_ = 0;
      extra_ = com.google.protobuf.ByteString.EMPTY;
      extraId_ = com.google.protobuf.ByteString.EMPTY;
      vmType_ = 0;
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private TransactionValue(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
              com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              price_ = input.readInt64();
              break;
            }
            case 16: {

              gasLimit_ = input.readInt64();
              break;
            }
            case 24: {

              amount_ = input.readInt64();
              break;
            }
            case 34: {

              payload_ = input.readBytes();
              break;
            }
            case 42: {

              encryptedAmount_ = input.readBytes();
              break;
            }
            case 50: {

              homomorphicAmount_ = input.readBytes();
              break;
            }
            case 58: {

              homomorphicBalance_ = input.readBytes();
              break;
            }
            case 64: {
              int rawValue = input.readEnum();

              op_ = rawValue;
              break;
            }
            case 74: {

              extra_ = input.readBytes();
              break;
            }
            case 82: {

              extraId_ = input.readBytes();
              break;
            }
            case 88: {
              int rawValue = input.readEnum();

              vmType_ = rawValue;
              break;
            }
            default: {
              if (!parseUnknownField(
                      input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
                e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
    getDescriptor() {
      return TransactionValueProto.internal_static_cn_hyperchain_sdk_rpc_Transaction_proto_TransactionValue_descriptor;
    }

    @Override
    protected FieldAccessorTable
    internalGetFieldAccessorTable() {
      return TransactionValueProto.internal_static_cn_hyperchain_sdk_rpc_Transaction_proto_TransactionValue_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                      TransactionValue.class, Builder.class);
    }

    /**
     * Protobuf enum {@code cn.hyperchain.sdk.rpc.Transaction.proto.TransactionValue.Opcode}
     */
    public enum Opcode
            implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>NORMAL = 0;</code>
       */
      NORMAL(0),
      /**
       * <code>UPDATE = 1;</code>
       */
      UPDATE(1),
      /**
       * <code>FREEZE = 2;</code>
       */
      FREEZE(2),
      /**
       * <code>UNFREEZE = 3;</code>
       */
      UNFREEZE(3),
      /**
       * <code>SKIPVM = 4;</code>
       */
      SKIPVM(4),
      /**
       * <code>ARCHIVE = 100;</code>
       */
      ARCHIVE(100),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>NORMAL = 0;</code>
       */
      public static final int NORMAL_VALUE = 0;
      /**
       * <code>UPDATE = 1;</code>
       */
      public static final int UPDATE_VALUE = 1;
      /**
       * <code>FREEZE = 2;</code>
       */
      public static final int FREEZE_VALUE = 2;
      /**
       * <code>UNFREEZE = 3;</code>
       */
      public static final int UNFREEZE_VALUE = 3;
      /**
       * <code>SKIPVM = 4;</code>
       */
      public static final int SKIPVM_VALUE = 4;
      /**
       * <code>ARCHIVE = 100;</code>
       */
      public static final int ARCHIVE_VALUE = 100;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new IllegalArgumentException(
                  "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @Deprecated
      public static Opcode valueOf(int value) {
        return forNumber(value);
      }

      public static Opcode forNumber(int value) {
        switch (value) {
          case 0: return NORMAL;
          case 1: return UPDATE;
          case 2: return FREEZE;
          case 3: return UNFREEZE;
          case 4: return SKIPVM;
          case 100: return ARCHIVE;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<Opcode>
      internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
              Opcode> internalValueMap =
              new com.google.protobuf.Internal.EnumLiteMap<Opcode>() {
                public Opcode findValueByNumber(int number) {
                  return Opcode.forNumber(number);
                }
              };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
        return TransactionValue.getDescriptor().getEnumTypes().get(0);
      }

      private static final Opcode[] VALUES = values();

      public static Opcode valueOf(
              com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new IllegalArgumentException(
                  "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private Opcode(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:cn.hyperchain.sdk.rpc.Transaction.proto.TransactionValue.Opcode)
    }

    /**
     * Protobuf enum {@code cn.hyperchain.sdk.rpc.Transaction.proto.TransactionValue.VmType}
     */
    public enum VmType
            implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>EVM = 0;</code>
       */
      EVM(0),
      /**
       * <code>JVM = 1;</code>
       */
      JVM(1),
      /**
       * <code>HVM = 2;</code>
       */
      HVM(2),
      /**
       * <code>BVM = 3;</code>
       */
      BVM(3),
      /**
       * <code>TRANSFER = 4;</code>
       */
      TRANSFER(4),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>EVM = 0;</code>
       */
      public static final int EVM_VALUE = 0;
      /**
       * <code>JVM = 1;</code>
       */
      public static final int JVM_VALUE = 1;
      /**
       * <code>HVM = 2;</code>
       */
      public static final int HVM_VALUE = 2;
      /**
       * <code>BVM = 3;</code>
       */
      public static final int BVM_VALUE = 3;
      /**
       * <code>TRANSFER = 4;</code>
       */
      public static final int TRANSFER_VALUE = 4;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new IllegalArgumentException(
                  "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @Deprecated
      public static VmType valueOf(int value) {
        return forNumber(value);
      }

      public static VmType forNumber(int value) {
        switch (value) {
          case 0: return EVM;
          case 1: return JVM;
          case 2: return HVM;
          case 3: return BVM;
          case 4: return TRANSFER;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<VmType>
      internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
              VmType> internalValueMap =
              new com.google.protobuf.Internal.EnumLiteMap<VmType>() {
                public VmType findValueByNumber(int number) {
                  return VmType.forNumber(number);
                }
              };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
        return TransactionValue.getDescriptor().getEnumTypes().get(1);
      }

      private static final VmType[] VALUES = values();

      public static VmType valueOf(
              com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new IllegalArgumentException(
                  "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private VmType(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:cn.hyperchain.sdk.rpc.Transaction.proto.TransactionValue.VmType)
    }

    public static final int PRICE_FIELD_NUMBER = 1;
    private long price_;
    /**
     * <code>int64 price = 1;</code>
     */
    public long getPrice() {
      return price_;
    }

    public static final int GASLIMIT_FIELD_NUMBER = 2;
    private long gasLimit_;
    /**
     * <code>int64 gasLimit = 2;</code>
     */
    public long getGasLimit() {
      return gasLimit_;
    }

    public static final int AMOUNT_FIELD_NUMBER = 3;
    private long amount_;
    /**
     * <code>int64 amount = 3;</code>
     */
    public long getAmount() {
      return amount_;
    }

    public static final int PAYLOAD_FIELD_NUMBER = 4;
    private com.google.protobuf.ByteString payload_;
    /**
     * <code>bytes payload = 4;</code>
     */
    public com.google.protobuf.ByteString getPayload() {
      return payload_;
    }

    public static final int ENCRYPTEDAMOUNT_FIELD_NUMBER = 5;
    private com.google.protobuf.ByteString encryptedAmount_;
    /**
     * <code>bytes encryptedAmount = 5;</code>
     */
    public com.google.protobuf.ByteString getEncryptedAmount() {
      return encryptedAmount_;
    }

    public static final int HOMOMORPHICAMOUNT_FIELD_NUMBER = 6;
    private com.google.protobuf.ByteString homomorphicAmount_;
    /**
     * <code>bytes homomorphicAmount = 6;</code>
     */
    public com.google.protobuf.ByteString getHomomorphicAmount() {
      return homomorphicAmount_;
    }

    public static final int HOMOMORPHICBALANCE_FIELD_NUMBER = 7;
    private com.google.protobuf.ByteString homomorphicBalance_;
    /**
     * <code>bytes homomorphicBalance = 7;</code>
     */
    public com.google.protobuf.ByteString getHomomorphicBalance() {
      return homomorphicBalance_;
    }

    public static final int OP_FIELD_NUMBER = 8;
    private int op_;
    /**
     * <code>.cn.hyperchain.sdk.rpc.Transaction.proto.TransactionValue.Opcode op = 8;</code>
     */
    public int getOpValue() {
      return op_;
    }
    /**
     * <code>.cn.hyperchain.sdk.rpc.Transaction.proto.TransactionValue.Opcode op = 8;</code>
     */
    public Opcode getOp() {
      @SuppressWarnings("deprecation")
      Opcode result = Opcode.valueOf(op_);
      return result == null ? Opcode.UNRECOGNIZED : result;
    }

    public static final int EXTRA_FIELD_NUMBER = 9;
    private com.google.protobuf.ByteString extra_;
    /**
     * <code>bytes extra = 9;</code>
     */
    public com.google.protobuf.ByteString getExtra() {
      return extra_;
    }

    public static final int EXTRAID_FIELD_NUMBER = 10;
    private com.google.protobuf.ByteString extraId_;
    /**
     * <code>bytes extraId = 10;</code>
     */
    public com.google.protobuf.ByteString getExtraId() {
      return extraId_;
    }

    public static final int VMTYPE_FIELD_NUMBER = 11;
    private int vmType_;
    /**
     * <code>.cn.hyperchain.sdk.rpc.Transaction.proto.TransactionValue.VmType vmType = 11;</code>
     */
    public int getVmTypeValue() {
      return vmType_;
    }
    /**
     * <code>.cn.hyperchain.sdk.rpc.Transaction.proto.TransactionValue.VmType vmType = 11;</code>
     */
    public VmType getVmType() {
      @SuppressWarnings("deprecation")
      VmType result = VmType.valueOf(vmType_);
      return result == null ? VmType.UNRECOGNIZED : result;
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
            throws java.io.IOException {
      if (price_ != 0L) {
        output.writeInt64(1, price_);
      }
      if (gasLimit_ != 0L) {
        output.writeInt64(2, gasLimit_);
      }
      if (amount_ != 0L) {
        output.writeInt64(3, amount_);
      }
      if (!payload_.isEmpty()) {
        output.writeBytes(4, payload_);
      }
      if (!encryptedAmount_.isEmpty()) {
        output.writeBytes(5, encryptedAmount_);
      }
      if (!homomorphicAmount_.isEmpty()) {
        output.writeBytes(6, homomorphicAmount_);
      }
      if (!homomorphicBalance_.isEmpty()) {
        output.writeBytes(7, homomorphicBalance_);
      }
      if (op_ != Opcode.NORMAL.getNumber()) {
        output.writeEnum(8, op_);
      }
      if (!extra_.isEmpty()) {
        output.writeBytes(9, extra_);
      }
      if (!extraId_.isEmpty()) {
        output.writeBytes(10, extraId_);
      }
      if (vmType_ != VmType.EVM.getNumber()) {
        output.writeEnum(11, vmType_);
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (price_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
                .computeInt64Size(1, price_);
      }
      if (gasLimit_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
                .computeInt64Size(2, gasLimit_);
      }
      if (amount_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
                .computeInt64Size(3, amount_);
      }
      if (!payload_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
                .computeBytesSize(4, payload_);
      }
      if (!encryptedAmount_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
                .computeBytesSize(5, encryptedAmount_);
      }
      if (!homomorphicAmount_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
                .computeBytesSize(6, homomorphicAmount_);
      }
      if (!homomorphicBalance_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
                .computeBytesSize(7, homomorphicBalance_);
      }
      if (op_ != Opcode.NORMAL.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
                .computeEnumSize(8, op_);
      }
      if (!extra_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
                .computeBytesSize(9, extra_);
      }
      if (!extraId_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
                .computeBytesSize(10, extraId_);
      }
      if (vmType_ != VmType.EVM.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
                .computeEnumSize(11, vmType_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
        return true;
      }
      if (!(obj instanceof TransactionValue)) {
        return super.equals(obj);
      }
      TransactionValue other = (TransactionValue) obj;

      if (getPrice()
              != other.getPrice()) return false;
      if (getGasLimit()
              != other.getGasLimit()) return false;
      if (getAmount()
              != other.getAmount()) return false;
      if (!getPayload()
              .equals(other.getPayload())) return false;
      if (!getEncryptedAmount()
              .equals(other.getEncryptedAmount())) return false;
      if (!getHomomorphicAmount()
              .equals(other.getHomomorphicAmount())) return false;
      if (!getHomomorphicBalance()
              .equals(other.getHomomorphicBalance())) return false;
      if (op_ != other.op_) return false;
      if (!getExtra()
              .equals(other.getExtra())) return false;
      if (!getExtraId()
              .equals(other.getExtraId())) return false;
      if (vmType_ != other.vmType_) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + PRICE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
              getPrice());
      hash = (37 * hash) + GASLIMIT_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
              getGasLimit());
      hash = (37 * hash) + AMOUNT_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
              getAmount());
      hash = (37 * hash) + PAYLOAD_FIELD_NUMBER;
      hash = (53 * hash) + getPayload().hashCode();
      hash = (37 * hash) + ENCRYPTEDAMOUNT_FIELD_NUMBER;
      hash = (53 * hash) + getEncryptedAmount().hashCode();
      hash = (37 * hash) + HOMOMORPHICAMOUNT_FIELD_NUMBER;
      hash = (53 * hash) + getHomomorphicAmount().hashCode();
      hash = (37 * hash) + HOMOMORPHICBALANCE_FIELD_NUMBER;
      hash = (53 * hash) + getHomomorphicBalance().hashCode();
      hash = (37 * hash) + OP_FIELD_NUMBER;
      hash = (53 * hash) + op_;
      hash = (37 * hash) + EXTRA_FIELD_NUMBER;
      hash = (53 * hash) + getExtra().hashCode();
      hash = (37 * hash) + EXTRAID_FIELD_NUMBER;
      hash = (53 * hash) + getExtraId().hashCode();
      hash = (37 * hash) + VMTYPE_FIELD_NUMBER;
      hash = (53 * hash) + vmType_;
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static TransactionValue parseFrom(
            java.nio.ByteBuffer data)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static TransactionValue parseFrom(
            java.nio.ByteBuffer data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static TransactionValue parseFrom(
            com.google.protobuf.ByteString data)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static TransactionValue parseFrom(
            com.google.protobuf.ByteString data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static TransactionValue parseFrom(byte[] data)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static TransactionValue parseFrom(
            byte[] data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static TransactionValue parseFrom(java.io.InputStream input)
            throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
              .parseWithIOException(PARSER, input);
    }
    public static TransactionValue parseFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
              .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static TransactionValue parseDelimitedFrom(java.io.InputStream input)
            throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
              .parseDelimitedWithIOException(PARSER, input);
    }
    public static TransactionValue parseDelimitedFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
              .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static TransactionValue parseFrom(
            com.google.protobuf.CodedInputStream input)
            throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
              .parseWithIOException(PARSER, input);
    }
    public static TransactionValue parseFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
              .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(TransactionValue prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
              ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
            BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code cn.hyperchain.sdk.rpc.Transaction.proto.TransactionValue}
     */
    public static final class Builder extends
            com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
            // @@protoc_insertion_point(builder_implements:cn.hyperchain.sdk.rpc.Transaction.proto.TransactionValue)
            TransactionValueOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
        return TransactionValueProto.internal_static_cn_hyperchain_sdk_rpc_Transaction_proto_TransactionValue_descriptor;
      }

      @Override
      protected FieldAccessorTable
      internalGetFieldAccessorTable() {
        return TransactionValueProto.internal_static_cn_hyperchain_sdk_rpc_Transaction_proto_TransactionValue_fieldAccessorTable
                .ensureFieldAccessorsInitialized(
                        TransactionValue.class, Builder.class);
      }

      // Construct using cn.hyperchain.sdk.rpc.Transaction.proto.TransactionValueProto.TransactionValue.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
              BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        price_ = 0L;

        gasLimit_ = 0L;

        amount_ = 0L;

        payload_ = com.google.protobuf.ByteString.EMPTY;

        encryptedAmount_ = com.google.protobuf.ByteString.EMPTY;

        homomorphicAmount_ = com.google.protobuf.ByteString.EMPTY;

        homomorphicBalance_ = com.google.protobuf.ByteString.EMPTY;

        op_ = 0;

        extra_ = com.google.protobuf.ByteString.EMPTY;

        extraId_ = com.google.protobuf.ByteString.EMPTY;

        vmType_ = 0;

        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
      getDescriptorForType() {
        return TransactionValueProto.internal_static_cn_hyperchain_sdk_rpc_Transaction_proto_TransactionValue_descriptor;
      }

      @Override
      public TransactionValue getDefaultInstanceForType() {
        return TransactionValue.getDefaultInstance();
      }

      @Override
      public TransactionValue build() {
        TransactionValue result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public TransactionValue buildPartial() {
        TransactionValue result = new TransactionValue(this);
        result.price_ = price_;
        result.gasLimit_ = gasLimit_;
        result.amount_ = amount_;
        result.payload_ = payload_;
        result.encryptedAmount_ = encryptedAmount_;
        result.homomorphicAmount_ = homomorphicAmount_;
        result.homomorphicBalance_ = homomorphicBalance_;
        result.op_ = op_;
        result.extra_ = extra_;
        result.extraId_ = extraId_;
        result.vmType_ = vmType_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
              com.google.protobuf.Descriptors.FieldDescriptor field,
              Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
              com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
              com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
              com.google.protobuf.Descriptors.FieldDescriptor field,
              int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
              com.google.protobuf.Descriptors.FieldDescriptor field,
              Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof TransactionValue) {
          return mergeFrom((TransactionValue)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(TransactionValue other) {
        if (other == TransactionValue.getDefaultInstance()) return this;
        if (other.getPrice() != 0L) {
          setPrice(other.getPrice());
        }
        if (other.getGasLimit() != 0L) {
          setGasLimit(other.getGasLimit());
        }
        if (other.getAmount() != 0L) {
          setAmount(other.getAmount());
        }
        if (other.getPayload() != com.google.protobuf.ByteString.EMPTY) {
          setPayload(other.getPayload());
        }
        if (other.getEncryptedAmount() != com.google.protobuf.ByteString.EMPTY) {
          setEncryptedAmount(other.getEncryptedAmount());
        }
        if (other.getHomomorphicAmount() != com.google.protobuf.ByteString.EMPTY) {
          setHomomorphicAmount(other.getHomomorphicAmount());
        }
        if (other.getHomomorphicBalance() != com.google.protobuf.ByteString.EMPTY) {
          setHomomorphicBalance(other.getHomomorphicBalance());
        }
        if (other.op_ != 0) {
          setOpValue(other.getOpValue());
        }
        if (other.getExtra() != com.google.protobuf.ByteString.EMPTY) {
          setExtra(other.getExtra());
        }
        if (other.getExtraId() != com.google.protobuf.ByteString.EMPTY) {
          setExtraId(other.getExtraId());
        }
        if (other.vmType_ != 0) {
          setVmTypeValue(other.getVmTypeValue());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
              com.google.protobuf.CodedInputStream input,
              com.google.protobuf.ExtensionRegistryLite extensionRegistry)
              throws java.io.IOException {
        TransactionValue parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (TransactionValue) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long price_ ;
      /**
       * <code>int64 price = 1;</code>
       */
      public long getPrice() {
        return price_;
      }
      /**
       * <code>int64 price = 1;</code>
       */
      public Builder setPrice(long value) {

        price_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 price = 1;</code>
       */
      public Builder clearPrice() {

        price_ = 0L;
        onChanged();
        return this;
      }

      private long gasLimit_ ;
      /**
       * <code>int64 gasLimit = 2;</code>
       */
      public long getGasLimit() {
        return gasLimit_;
      }
      /**
       * <code>int64 gasLimit = 2;</code>
       */
      public Builder setGasLimit(long value) {

        gasLimit_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 gasLimit = 2;</code>
       */
      public Builder clearGasLimit() {

        gasLimit_ = 0L;
        onChanged();
        return this;
      }

      private long amount_ ;
      /**
       * <code>int64 amount = 3;</code>
       */
      public long getAmount() {
        return amount_;
      }
      /**
       * <code>int64 amount = 3;</code>
       */
      public Builder setAmount(long value) {

        amount_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 amount = 3;</code>
       */
      public Builder clearAmount() {

        amount_ = 0L;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString payload_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes payload = 4;</code>
       */
      public com.google.protobuf.ByteString getPayload() {
        return payload_;
      }
      /**
       * <code>bytes payload = 4;</code>
       */
      public Builder setPayload(com.google.protobuf.ByteString value) {
        if (value == null) {
          throw new NullPointerException();
        }

        payload_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes payload = 4;</code>
       */
      public Builder clearPayload() {

        payload_ = getDefaultInstance().getPayload();
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString encryptedAmount_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes encryptedAmount = 5;</code>
       */
      public com.google.protobuf.ByteString getEncryptedAmount() {
        return encryptedAmount_;
      }
      /**
       * <code>bytes encryptedAmount = 5;</code>
       */
      public Builder setEncryptedAmount(com.google.protobuf.ByteString value) {
        if (value == null) {
          throw new NullPointerException();
        }

        encryptedAmount_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes encryptedAmount = 5;</code>
       */
      public Builder clearEncryptedAmount() {

        encryptedAmount_ = getDefaultInstance().getEncryptedAmount();
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString homomorphicAmount_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes homomorphicAmount = 6;</code>
       */
      public com.google.protobuf.ByteString getHomomorphicAmount() {
        return homomorphicAmount_;
      }
      /**
       * <code>bytes homomorphicAmount = 6;</code>
       */
      public Builder setHomomorphicAmount(com.google.protobuf.ByteString value) {
        if (value == null) {
          throw new NullPointerException();
        }

        homomorphicAmount_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes homomorphicAmount = 6;</code>
       */
      public Builder clearHomomorphicAmount() {

        homomorphicAmount_ = getDefaultInstance().getHomomorphicAmount();
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString homomorphicBalance_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes homomorphicBalance = 7;</code>
       */
      public com.google.protobuf.ByteString getHomomorphicBalance() {
        return homomorphicBalance_;
      }
      /**
       * <code>bytes homomorphicBalance = 7;</code>
       */
      public Builder setHomomorphicBalance(com.google.protobuf.ByteString value) {
        if (value == null) {
          throw new NullPointerException();
        }

        homomorphicBalance_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes homomorphicBalance = 7;</code>
       */
      public Builder clearHomomorphicBalance() {

        homomorphicBalance_ = getDefaultInstance().getHomomorphicBalance();
        onChanged();
        return this;
      }

      private int op_ = 0;
      /**
       * <code>.cn.hyperchain.sdk.rpc.Transaction.proto.TransactionValue.Opcode op = 8;</code>
       */
      public int getOpValue() {
        return op_;
      }
      /**
       * <code>.cn.hyperchain.sdk.rpc.Transaction.proto.TransactionValue.Opcode op = 8;</code>
       */
      public Builder setOpValue(int value) {
        op_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.cn.hyperchain.sdk.rpc.Transaction.proto.TransactionValue.Opcode op = 8;</code>
       */
      public Opcode getOp() {
        @SuppressWarnings("deprecation")
        Opcode result = Opcode.valueOf(op_);
        return result == null ? Opcode.UNRECOGNIZED : result;
      }
      /**
       * <code>.cn.hyperchain.sdk.rpc.Transaction.proto.TransactionValue.Opcode op = 8;</code>
       */
      public Builder setOp(Opcode value) {
        if (value == null) {
          throw new NullPointerException();
        }

        op_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.cn.hyperchain.sdk.rpc.Transaction.proto.TransactionValue.Opcode op = 8;</code>
       */
      public Builder clearOp() {

        op_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString extra_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes extra = 9;</code>
       */
      public com.google.protobuf.ByteString getExtra() {
        return extra_;
      }
      /**
       * <code>bytes extra = 9;</code>
       */
      public Builder setExtra(com.google.protobuf.ByteString value) {
        if (value == null) {
          throw new NullPointerException();
        }

        extra_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes extra = 9;</code>
       */
      public Builder clearExtra() {

        extra_ = getDefaultInstance().getExtra();
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString extraId_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes extraId = 10;</code>
       */
      public com.google.protobuf.ByteString getExtraId() {
        return extraId_;
      }
      /**
       * <code>bytes extraId = 10;</code>
       */
      public Builder setExtraId(com.google.protobuf.ByteString value) {
        if (value == null) {
          throw new NullPointerException();
        }

        extraId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes extraId = 10;</code>
       */
      public Builder clearExtraId() {

        extraId_ = getDefaultInstance().getExtraId();
        onChanged();
        return this;
      }

      private int vmType_ = 0;
      /**
       * <code>.cn.hyperchain.sdk.rpc.Transaction.proto.TransactionValue.VmType vmType = 11;</code>
       */
      public int getVmTypeValue() {
        return vmType_;
      }
      /**
       * <code>.cn.hyperchain.sdk.rpc.Transaction.proto.TransactionValue.VmType vmType = 11;</code>
       */
      public Builder setVmTypeValue(int value) {
        vmType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.cn.hyperchain.sdk.rpc.Transaction.proto.TransactionValue.VmType vmType = 11;</code>
       */
      public VmType getVmType() {
        @SuppressWarnings("deprecation")
        VmType result = VmType.valueOf(vmType_);
        return result == null ? VmType.UNRECOGNIZED : result;
      }
      /**
       * <code>.cn.hyperchain.sdk.rpc.Transaction.proto.TransactionValue.VmType vmType = 11;</code>
       */
      public Builder setVmType(VmType value) {
        if (value == null) {
          throw new NullPointerException();
        }

        vmType_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.cn.hyperchain.sdk.rpc.Transaction.proto.TransactionValue.VmType vmType = 11;</code>
       */
      public Builder clearVmType() {

        vmType_ = 0;
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
              final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
              final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:cn.hyperchain.sdk.rpc.Transaction.proto.TransactionValue)
    }

    // @@protoc_insertion_point(class_scope:cn.hyperchain.sdk.rpc.Transaction.proto.TransactionValue)
    private static final TransactionValue DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new TransactionValue();
    }

    public static TransactionValue getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<TransactionValue>
            PARSER = new com.google.protobuf.AbstractParser<TransactionValue>() {
      @Override
      public TransactionValue parsePartialFrom(
              com.google.protobuf.CodedInputStream input,
              com.google.protobuf.ExtensionRegistryLite extensionRegistry)
              throws com.google.protobuf.InvalidProtocolBufferException {
        return new TransactionValue(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<TransactionValue> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<TransactionValue> getParserForType() {
      return PARSER;
    }

    @Override
    public TransactionValue getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
          internal_static_cn_hyperchain_sdk_rpc_Transaction_proto_TransactionValue_descriptor;
  private static final
  com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internal_static_cn_hyperchain_sdk_rpc_Transaction_proto_TransactionValue_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
  getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
          descriptor;
  static {
    String[] descriptorData = {
            "\n\021transaction.proto\022\'cn.hyperchain.sdk.r" +
                    "pc.Transaction.proto\"\365\003\n\020TransactionValu" +
                    "e\022\r\n\005price\030\001 \001(\003\022\020\n\010gasLimit\030\002 \001(\003\022\016\n\006am" +
                    "ount\030\003 \001(\003\022\017\n\007payload\030\004 \001(\014\022\027\n\017encrypted" +
                    "Amount\030\005 \001(\014\022\031\n\021homomorphicAmount\030\006 \001(\014\022" +
                    "\032\n\022homomorphicBalance\030\007 \001(\014\022L\n\002op\030\010 \001(\0162" +
                    "@.cn.hyperchain.sdk.rpc.Transaction.prot" +
                    "o.TransactionValue.Opcode\022\r\n\005extra\030\t \001(\014" +
                    "\022\017\n\007extraId\030\n \001(\014\022P\n\006vmType\030\013 \001(\0162@.cn.h" +
                    "yperchain.sdk.rpc.Transaction.proto.Tran" +
                    "sactionValue.VmType\"S\n\006Opcode\022\n\n\006NORMAL\020" +
                    "\000\022\n\n\006UPDATE\020\001\022\n\n\006FREEZE\020\002\022\014\n\010UNFREEZE\020\003\022" +
                    "\n\n\006SKIPVM\020\004\022\013\n\007ARCHIVE\020d\":\n\006VmType\022\007\n\003EV" +
                    "M\020\000\022\007\n\003JVM\020\001\022\007\n\003HVM\020\002\022\007\n\003BVM\020\003\022\014\n\010TRANSF" +
                    "ER\020\004B@\n\'cn.hyperchain.sdk.rpc.Transactio" +
                    "n.protoB\025TransactionValueProtob\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
            new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
              public com.google.protobuf.ExtensionRegistry assignDescriptors(
                      com.google.protobuf.Descriptors.FileDescriptor root) {
                descriptor = root;
                return null;
              }
            };
    com.google.protobuf.Descriptors.FileDescriptor
            .internalBuildGeneratedFileFrom(descriptorData,
                    new com.google.protobuf.Descriptors.FileDescriptor[] {
                    }, assigner);
    internal_static_cn_hyperchain_sdk_rpc_Transaction_proto_TransactionValue_descriptor =
            getDescriptor().getMessageTypes().get(0);
    internal_static_cn_hyperchain_sdk_rpc_Transaction_proto_TransactionValue_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_cn_hyperchain_sdk_rpc_Transaction_proto_TransactionValue_descriptor,
            new String[] { "Price", "GasLimit", "Amount", "Payload", "EncryptedAmount", "HomomorphicAmount", "HomomorphicBalance", "Op", "Extra", "ExtraId", "VmType", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
